### ISSUE TITLE
Not published on npm

### ISSUE THREAD

**Issue by MystK** [emilol/angular2-crumbs#16]
Hi there, I was interested in using v2 and v3 but they are not published on npm. Will they be published?

**Comment by emilol** [comment]
Hi - are you looking at `angular2-crumbs` or `angular-crumbs`? The latter is the package for Angular 4 and up.

**Comment by MystK** [comment]
Thank you. I did not realize that there was a different NPM package name! 😊
________________________________

**Comment by emilol** [comment]
No worries, and thanks for asking! I've added a warning to the older package to help people out in the future.
