### ISSUE TITLE
breadcrumb not working properly with lazyloading

### ISSUE THREAD

**Issue by Hasan-git** [emilol/angular2-crumbs#18]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

In my project most of my routes are lazy loaded, when I try to load the website for the first time the breadcrumb element displays nothing. but, after navigating to next page the breadcrumb element displays routes normally as usual.

## Expected behavior

breadcrumb element should display route breadcrumb data on website load even if route is lazy loaded

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version:  v10.13.0
- Platform:   Windows 

Others:

</code></pre>

**Comment by emilol** [comment]
Hi Hasan, thanks for reporting this. 

angular-crumbs is a labor of love done completely in my spare time. Unfortunately I don't have the luxury of spending time reproducing issues reported, which is why I've included the section "Minimal reproduction of the problem with instructions" in the issue template.

Closing issue as it doesn't follow the issue template. Please feel free to resubmit including a minimal reproduction in something like plunkr or stackblitz.

**Comment by sK-1005** [comment]
There is a simple solution to this.

Track the last index in the *ngfor loop of the breadCrumb component.

Angular exposes local variables for ngfor to track elements of the loop.

https://angular.io/api/common/NgForOf

Replace the customizable code mentioned in the angular-crumbs customizable code. I am demonstrating below using a bootstrap example.

From:

<breadcrumb #parent>
   <ol class="breadcrumb">
     <ng-template ngFor let-route [ngForOf]="parent.breadcrumbs">
       <li *ngIf="!route.terminal" class="breadcrumb-item">
         <a href="" [routerLink]="[route.url]">{{ route.displayName }}</a>
       </li>
       <li *ngIf="route.terminal" class="breadcrumb-item active" aria-current="page"> 
            {{ route.displayName }}</li>
     </ng-template>
   </ol>
</breadcrumb> }

Change To:

<breadcrumb #parent>
   <ol class="breadcrumb">
     <ng-template ngFor let-route [ngForOf]="parent.breadcrumbs" let-lastIndex="last">
       <li *ngIf="!lastIndex" class="breadcrumb-item">
         <a href="" [routerLink]="[route.url]">{{ route.displayName }}</a>
       </li>
       <li *ngIf="lastIndex" class="breadcrumb-item active" aria-current="page"> 
            {{ route.displayName }}</li>
     </ng-template>
   </ol>
</breadcrumb> }
The value of lastIndex will be a boolean value. Here, when we know the breadcrumb ngfor loop is at last value, mark it as active.

That is how you usethe @emilol 's fantastic angular-crumbs library  with Lazy Loading. Let me know if you need an example.

**Comment by sK-1005** [comment]
There is a simple Solution  to this.

Track the last index in the *ngfor loop of the breadCrumb component.

Angular exposes local variables for ngfor to track elements of the loop.

https://angular.io/api/common/NgForOf

Replace the customizable code mentioned in the angular-crumbs npm page. I am demonstrating below using a bootstrap example. Once you implemented lazy loading, just change the below code in the customizable bootstrap example.

      <ng-template ngFor let-route [ngForOf]="parent.breadcrumbs" let-lastIndex="last">
        <li *ngIf="!lastIndex" class="breadcrumb-item">
          <a [routerLink]="[route.url]">{{ route.displayName }}</a>
       </li>
       <li *ngIf="lastIndex" class="breadcrumb-item active" aria-current="page"> route.displayName </li>
     </ng-template>
   
The value of lastIndex will be a boolean value. Here, when we know the breadcrumb ngfor loop is at last value, mark it as active.

That is how you solve @emilol 's fantastic angular-crumbs library compatibility with Lazy Loading. Let me know if you need an example.
