### ISSUE TITLE
when i eject ng serve, ERROR in BreadcrumbModule is not an NgModule     

### ISSUE THREAD

**Issue by jolugama** [emilol/angular2-crumbs#3]
I have to save any file and then works.
 angular/cli 1.1.3

**Comment by demiro** [comment]
the same for me, very annoying

Actually now that I upgraded to
@angular/cli ^1.4.2

webpack doesn't even compile :'(

**Comment by emilol** [comment]
Hi there! 

Were you able to resolve this issue? If not please verify you are following the documentation for the relevant npm package, (`angular-crumbs` not `angular2-crumbs` if you are using the latest).

I'm going to close this issue, if you still have an issue after reviewing the doco please resubmit using the issue template.
