### ISSUE TITLE
Error after run ne serve 

### ISSUE THREAD

**Issue by maspasov** [emilol/angular2-crumbs#6]
`ERROR in Error encountered resolving symbol values statically. Calling function 'BreadcrumbModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in C:/project/src/app/app.module.ts, resolving symbol AppModule in C:/project/src/app/app.module.ts`

If I save any files everything works.

**Comment by emilol** [comment]
Hi there! 

Were you able to resolve this issue? If not please verify you are following the documentation for the relevant npm package, (`angular-crumbs` not `angular2-crumbs` if you are using the latest).

I'm going to close this issue, if you still have an issue after reviewing the doco please resubmit using the issue template.
